# Generated by Django 2.0.4 on 2018-04-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['-votes']},
        ),
        migrations.AddField(
            model_name='choice',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
